### ISSUE TITLE
Support SSH Keyfiles with password

### ISSUE THREAD

**Issue by xopez** [TitusKirch/webBackup#8]
**Is your feature request related to a problem? Please describe.**
Not a problem. I want to backup over my local Rasperry Pi to my NAS. And I don't want to enable password authentification.

**Describe the solution you'd like**
Allow adding the path of a keyfile and the password for the keyfile.

**Additional context**
It's just more secure with keys.

**Comment by TitusKirch** [comment]
SSH keys are already supported, but currently it is not possible to configure a path to it (which can cause problems with multiple SSH keys).

I don't know if SSH keys with passphrase are already supported, but I'll have a look.

**Comment by xopez** [comment]
For explanation: I consider the generation of key files without a password to be grossly negligent. Once the key is gone, you can simply enter the server. There is a security level so that no one can access it directly. Of course I have to set this up at Raspi. But he's on the internal network and he's not world-open.

I wait for it :)

**Comment by TitusKirch** [comment]
As for your statement, I agree with it in principle. However, up to now this script has only been used in the following scenario:

Server A (with SSH key) makes a backup and logs on to server B. Since server A would need the key and the passphrase anyway, I think it is possible to omit the passphrase, because if a third party had access to the system and got the SSH key, he would get the passphrase.

**Comment by TitusKirch** [comment]
You can now specify the SSH key c1153e2
